### ISSUE TITLE
Comments fail it("should not use complex math")

### ISSUE THREAD

**Issue by Koji23** [JS-Challenges/recursion-prompts#40]
First off thanks for this challenge set!

So I just noticed that adding in-function comments to Modulo, Multiply, and Divide is caught by the search for '/' operators. Not sure if its worth changing the test for it but a warning above the prompt might be nice.

Best,
Jordan

**Comment by mybrainishuge** [comment]
Thanks for the feedback!  I always like receiving feedback about this repo.  This particular test is scrubbing the function for '/' which includes comments.  Part of solving a problem is opening the spec files and deciphering them.  I know that sounds like a cheap excuse for not writing more robust tests, but it's true.  For example, I think the quirk you mentioned isn't actually the most puzzling element of the divide prompt.  In order to understand how it's testing, you have to open the spec to discover it's using the ~ symbol to do something funky.  I intentionally didn't explain this part because I want the student to do the research.  Thanks again for the feedback!  I hope you're finding the prompts helpful.
