### ISSUE TITLE
Recursion Test - Part 1 (Exponent)

### ISSUE THREAD

**Issue by Asalem1** [JS-Challenges/recursion-prompts#55]
First off, I wanted to say thanks for setting this up, it's been a huge help in practicing recursion! I just wanted to point out a slight issue with one of the tests (lines 435-440) in Part I. A negative base with an even exponent will yield a positive number.

it('should accept negative integer for base', function() {
   expect(exponent(-3,4)).to.equal(-81); //should be 81
   expect(exponent(-12,5)).to.equal(-248832);
   expect(exponent(-7,2)).to.equal(-49); //should be 49
   expect(exponent(-7,4)).to.equal(-2401); //should be 2401
});

**Comment by mybrainishuge** [comment]
Hey, @Asalem1 glad you're enjoying the repo! I concede to your math. Since JS is known to struggle with math, I suspect I used Google or some other calculator and failed to include parens around the negative number. Note the difference:
[https://www.google.com/#q=-3^4](https://www.google.com/#q=-3^4)
[https://www.google.com/#q=(-3)^4](https://www.google.com/#q=(-3)^4)

Would you like to make a PR with the fix?

**Comment by ejk91** [comment]
If @Asalem1 doesn't mind, I can submit a PR with the fix!

**Comment by mybrainishuge** [comment]
That'd be great, @ejk91 !

**Comment by ejk91** [comment]
PR submitted!

**Comment by mybrainishuge** [comment]
Thanks, @ejk91 ! PR #56 has been merged.

**Comment by Asalem1** [comment]
@mybrainishuge Sorry about that, not sure how I didn't see the notification. Happy to hear it all worked out!
