### ISSUE TITLE
isEven -- Modulo issue

### ISSUE THREAD

**Issue by erictessin** [JS-Challenges/recursion-prompts#83]
Test will fail for "should not use modulo" when the word "modulo" is included in comments.

**Comment by mybrainishuge** [comment]
Thanks for your feedback, @erictessin. Do you have a suggested solution for improving this test?

**Comment by erictessin** [comment]
Hey @mybrainishuge!

Maybe delete this line in the test? 

`expect(stringified).to.not.contain('modulo');`

Unless there is a way to calculate the remainder using the word "modulo" that i don't know about, I don't see why including the word should make the test fail. But maybe I'm missing something?

**Comment by mybrainishuge** [comment]
One of the challenges is to write a function called [`modulo`](https://github.com/JS-Challenges/recursion-prompts/blob/master/src/recursion.js#L65). The test you referenced is attempting to prevent you from using that function.
```
var isEven = function(n) {
    return modulo(n % 2) === 0
};
```
^^^ This misses the point of the exercise since `isEven` doesn't call itself. Keep in mind that these challenges aren't expected to be performant, but rather force you to utilize recursion. More specifically, each function must call itself.

What's a base case for even or odd and how do you reach that base case? Think about `factorial` if you've already implemented that one. Given `n`, what can you do to `n` repeatedly until the base case is reached to determine the answer?

Does that help?

**Comment by mybrainishuge** [comment]
I made a [change](https://github.com/JS-Challenges/recursion-prompts/commit/568c9c91df714e654461de91a616f9fb033fb043) to the check for `modulo`, but using it by name or operator is still forbidden when implementing `isEven`. I'm going to close this issue, but feel free to reach out if you have more questions.

**Comment by erictessin** [comment]
That does clear it up! Thank you Richard. I've been enjoying the exercises,
they're super helpful.

Best regards,
Eric T
